services:
  app:
    image: frontend-todo
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml", this means mount ./ to usr/src/app
    ports:
      - 3000:3000
    container_name: frontend-todo # This will name the container todo-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: proxy-reverse
    depends_on:
      - app # wait for the frontend container to be started